### ISSUE TITLE
[BUG?] PARTS, Drag and Drop functionality not working smoothly

### ISSUE THREAD

**Issue by auphofBSF** [turdusmerula/kipartman#8]
Dragging part over  category items (Left pane) indicates no options 
![image](https://user-images.githubusercontent.com/11743864/33049113-64e73da0-cec3-11e7-940d-18dddabcf94c.png)

However dragged to the top of frame displays + on the floating tooltip and then usually drags into the top most displayed category but not always 
![image](https://user-images.githubusercontent.com/11743864/33049145-91e9b4c2-cec3-11e7-9e0b-cb276ad411ea.png)

Trying to debug various other issues with Drag and Drop . I have some patches that improve error handling and debugging I will publish as pull requests, but as yet no solution.

**Comment by auphofBSF** [comment]
added a pull request  https://github.com/turdusmerula/kipartman/pull/9   **Issue#8 parts dragand drop**

This has some error fixes and additional debugging support via logging

**Comment by turdusmerula** [comment]
Great ! It was part of the TODO list inside tree.py.
Did you managed to have a proper cursor handling on Windows for accepted/rejected drop targets? 
If yes, it doesn't seems to work very well on Linux, we may have to implement platform specific handling for this part.

I corrected the problem that occurred when dropping a part to itself on #7 and improved backend error reporting (we still had a 200 response when an error was detected, now we have a 403).

**Comment by auphofBSF** [comment]
I have only managed to clear up some of the code crashing issues, with the last pull request #9 

I still cannot drag a part on to a category dataview line item. 
At present on windows all treecategories lines are showing rejected only the outside frame (Header row) accepts drops where  but Cursor is showing as acopy not move.  
I am not familiar with wxPython so trying to get my head around it with some test code.

**Comment by turdusmerula** [comment]
This problem looks specific either to Windows or to wxPython version.
I have it working on Linux with wxPython 4.0.0b2, I will have to take some time to create a testing environment with a kicad compatible version for further testing.

**Comment by auphofBSF** [comment]
I have temporarily disabled the requirement for pcbnew so am testing against both wxPython 3 and 4 om MSW10 . I will try tomorrow on a ubuntu 16 Virtualbox instance.

**Comment by auphofBSF** [comment]
Finally some success, with DnD.  However the changes in tree.py might only suite MSW. I will need to check these changes in a linux enviroment. Until they are checked I will not issue a Pull request, and leave the changes in the branch created issue#8-FIXTEST. 
Nice work @turdusmerula on the parts parameters display/filtering/flattening,  #5 and #3 have not looked in detail but will be very useful.

**Comment by turdusmerula** [comment]
If the merge is okay for MSW we can close this bug, I haven't seen any problem on Ubuntu.

**Comment by auphofBSF** [comment]
Very Happy to close, drag and drop functionally working also tested in foot print tree
